### ISSUE TITLE
Milestone 2 feedback:

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1049#3]
Must fix:

- [x] Use data chaining in your project_functions.py
- [x] Use markdown formatting in order to stylize your Task5.ipynb
- [x] add units/titles to the graphs 
- [x] add more analysis to task 5 in order to make it more thorough
